import { useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Check, Code, Copy, FileImage, Feather, ImagePlus, Plus, Trash2 } from 'lucide-react';
import Modal from './Modal';
import { SpellIcon } from './Icons';
import { iconNames, parseSpell, spellSchema, spellSource } from './spells';
import type { Block, Spell } from './spells';
import type { EditSection } from './Book';

export async function copyText(text: string) {
  try { await navigator.clipboard.writeText(text); return true; } catch { return false; }
}
export default function Editor({ spell, initialSection, isNew, onSave, onClose, onDelete, notify }: { spell: Spell; initialSection: EditSection; isNew: boolean; onSave: (spell: Spell) => string | null; onClose: () => void; onDelete?: () => void; notify: (message: string) => void }) {
  const [draft,setDraft]=useState<Spell>(()=>structuredClone(spell));
  const [source,setSource]=useState(()=>spellSource(spell));
  const [section,setSection]=useState(initialSection);
  const [error,setError]=useState('');
  const [discard,setDiscard]=useState(false);
  const [deleting,setDeleting]=useState(false);
  const upload=useRef<HTMLInputElement>(null);
  const update=<K extends keyof Spell>(key:K,value:Spell[K])=>setDraft(d=>({...d,[key]:value}));
  const changeSection=(next:EditSection)=>{if(next===section)return;setError('');if(section==='code'){try{setDraft(parseSpell(source));}catch(e){setError((e as Error).message);return;}}if(next==='code')setSource(spellSource(draft));setSection(next);};
  const close=()=>{const dirty=JSON.stringify(draft)!==JSON.stringify(spell)||(section==='code'&&source!==spellSource(spell));if(dirty)setDiscard(true);else onClose();};
  const save=()=>{try{const result=section==='code'?parseSpell(source):spellSchema.parse(draft);const problem=onSave(result);if(problem)setError(problem);}catch(e){setError(e instanceof Error?e.message:'This spell could not be read.');}};
  const addBlock=(kind:'text'|'image')=>{if(draft.blocks.length>=8){setError('A spell can hold up to eight additional notes or images.');return;}update('blocks',[...draft.blocks,kind==='text'?{id:crypto.randomUUID(),kind,placement:'after',content:'A new observation…'}:{id:crypto.randomUUID(),kind,placement:'after',content:'',caption:''}]);};
  const updateBlock=(id:string,fields:Partial<Block>)=>update('blocks',draft.blocks.map(b=>b.id===id?{...b,...fields} as Block:b));
  const moveBlock=(i:number,step:number)=>{const blocks=[...draft.blocks];[blocks[i],blocks[i+step]]=[blocks[i+step],blocks[i]];update('blocks',blocks);};
  const imageUpload=(file:File)=>{
    if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){setError('Choose a PNG, JPEG, WebP, or GIF image.');return;}
    if(file.size>1000000){setError('Please choose an image smaller than 1 MB so your tome can be saved on this device.');return;}
    if(draft.blocks.length>=8){setError('A spell can hold up to eight additional notes or images.');return;}
    const reader=new FileReader();reader.onload=()=>setDraft(d=>({...d,blocks:[...d.blocks,{id:crypto.randomUUID(),kind:'image',placement:'after',content:reader.result as string,caption:file.name.replace(/\.[^.]+$/,'') }].slice(0,8) as Block[]}));reader.onerror=()=>setError('This image could not be read.');reader.readAsDataURL(file);
  };
  return <Modal title={isNew?'Inscribe a spell':'Refine your spell'} subtitle={isNew?'A blank leaf. An entirely new possibility.':`Revisit the words that bring ${spell.title} to life.`} onClose={close} wide>
    {discard?<div className="confirmation"><h3>Leave these words unwritten?</h3><p>Your changes have not been saved.</p><div className="button-row"><button className="gold-button" onClick={()=>setDiscard(false)}>Keep writing</button><button className="quiet-button" onClick={onClose}>Discard changes</button></div></div>:deleting?<div className="confirmation"><h3>Remove {spell.title} from the tome?</h3><p>This removes its pages and quick-slot bindings. Export your tome first if you want a copy.</p><div className="button-row"><button className="gold-button" onClick={()=>setDeleting(false)}>Keep this spell</button><button className="danger-button" onClick={onDelete}>Remove spell</button></div></div>:<>
      <div className="editor-tabs" role="tablist" aria-label="Spell editor sections"><button role="tab" aria-selected={section==='details'} onClick={()=>changeSection('details')}><Feather size={16}/> Inscription</button><button role="tab" aria-selected={section==='code'} onClick={()=>changeSection('code')}><Code size={16}/> Spell code</button><button role="tab" aria-selected={section==='extras'} onClick={()=>changeSection('extras')}><FileImage size={16}/> Notes & images</button></div>
      <div className="editor-body" role="tabpanel">
        {section==='details'&&<div className="editor-fields"><div className="field-row"><label>Spell title<input maxLength={80} value={draft.title} onChange={e=>update('title',e.target.value)}/></label><label>School<input maxLength={40} value={draft.school} onChange={e=>update('school',e.target.value)}/></label></div><label>A line beneath the title<input maxLength={100} value={draft.subtitle} onChange={e=>update('subtitle',e.target.value)}/></label><div className="symbol-color-row"><fieldset><legend>Spell symbol</legend><div className="icon-options">{iconNames.map(icon=><button key={icon} aria-label={`${icon} symbol`} aria-pressed={draft.icon===icon} className={draft.icon===icon?'chosen':''} onClick={()=>update('icon',icon)}><SpellIcon spell={{icon}} size={21}/></button>)}</div></fieldset><label className="color-field">Ink color<input aria-label="Ink color" type="color" value={draft.color} onChange={e=>update('color',e.target.value)}/></label></div><label>Description<textarea rows={5} maxLength={3000} value={draft.description} onChange={e=>update('description',e.target.value)}/></label><label>Notes in the margin<textarea className="handwritten-input" rows={3} maxLength={3000} value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label></div>}
        {section==='code'&&<div className="code-editor"><div className="code-toolbar"><p>Paste a complete spell from your LLM, or write the JavaScript yourself.</p><button className="quiet-button" onClick={async()=>{notify(await copyText(source)?'Spell code copied.':'Clipboard unavailable. Select the spell code and copy it manually.');}}><Copy size={15}/> Copy</button></div><label className="sr-only" htmlFor="spell-source">Spell JavaScript code</label><textarea id="spell-source" className="source-textarea" spellCheck={false} value={source} onChange={e=>{setSource(e.target.value);setError('');}}/><p className="field-help">Paste the metadata header and JavaScript together, with or without a javascript code fence. Code runs when you cast and has access to this page; import code you trust.</p></div>}
        {section==='extras'&&<div className="extras-editor"><p className="field-help">Place notes and illustrations before the description or after the incantation. Change their order with the arrows.</p>{draft.blocks.length===0&&<div className="empty-extras"><Feather size={32}/><p>Some discoveries belong in the margins.</p><small>Add a field note, a diagram, or a memory.</small></div>}{draft.blocks.map((block,i)=><div className="block-editor" key={block.id}><div className="block-toolbar"><span>{block.kind==='text'?'Field note':'Illustration'} {i+1}</span><select aria-label={`Placement for block ${i+1}`} value={block.placement} onChange={e=>updateBlock(block.id,{placement:e.target.value as 'before'|'after'})}><option value="before">Before description</option><option value="after">After incantation</option></select><button className="icon-button" aria-label={`Move block ${i+1} up`} disabled={i===0} onClick={()=>moveBlock(i,-1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`Move block ${i+1} down`} disabled={i===draft.blocks.length-1} onClick={()=>moveBlock(i,1)}><ArrowDown size={15}/></button><button className="icon-button" aria-label={`Remove block ${i+1}`} onClick={()=>update('blocks',draft.blocks.filter(b=>b.id!==block.id))}><Trash2 size={15}/></button></div>{block.kind==='text'?<label>Note text<textarea rows={3} value={block.content} maxLength={3000} onChange={e=>updateBlock(block.id,{content:e.target.value})}/></label>:<><label>Image URL{block.content.startsWith('data:')?<span className="uploaded-image-label">Uploaded image · saved in your tome</span>:<input type="url" placeholder="https://…" value={block.content} onChange={e=>updateBlock(block.id,{content:e.target.value})}/>}</label>{block.content&&/^(https?:\/\/|data:image\/(png|jpeg|webp|gif);base64,)/i.test(block.content)&&<img className="editor-image-preview" src={block.content} alt={block.caption||'Illustration preview'}/>}<label>Caption<input maxLength={200} value={block.caption} onChange={e=>updateBlock(block.id,{caption:e.target.value})}/></label></>}</div>)}<div className="button-row"><button className="gold-button" onClick={()=>addBlock('text')}><Plus size={15}/> Add note</button><button className="quiet-button" onClick={()=>addBlock('image')}><ImagePlus size={16}/> Image link</button><button className="quiet-button" onClick={()=>upload.current?.click()}><FileImage size={16}/> Upload image</button><input className="sr-only" ref={upload} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{if(e.target.files?.[0])imageUpload(e.target.files[0]);e.target.value='';}}/></div></div>}
        {error&&<pre className="form-error" role="alert">{error}</pre>}
      </div><div className="editor-footer"><div>{onDelete&&<button className="quiet-button danger-text" onClick={()=>setDeleting(true)}><Trash2 size={15}/> Remove spell</button>}</div><div className="button-row"><button className="quiet-button" onClick={close}>Cancel</button><button className="gold-button primary" onClick={save}><Check size={16}/> {isNew?'Add to grimoire':'Save changes'}</button></div></div>
    </>}
  </Modal>;
}
